name: CI

on:
  push:
    branches:
      - master
      - "v*"
    tags:
      - "v*"
  pull_request:
  schedule:
    - cron: '0 3 * * *' # daily, at 3am

jobs:
  tests:
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - "3.9"
          - "3.8"
          - "3.7"
          - "3.6"
          - "3.5"
          - "2.7"


    name: "Tests (Python v${{ matrix.python-version }}."
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install -r requirements.txt

      - run: pytest -v --cov=utm --color=yes


